/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jfgiraud_jlinenoise_Example */

#ifndef _Included_com_github_jfgiraud_jlinenoise_Example
#define _Included_com_github_jfgiraud_jlinenoise_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jfgiraud_jlinenoise_Example
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jfgiraud_jlinenoise_Example_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
