/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jfgiraud_jlinenoise_JLinenoiseLibrary */

#ifndef _Included_com_github_jfgiraud_jlinenoise_JLinenoiseLibrary
#define _Included_com_github_jfgiraud_jlinenoise_JLinenoiseLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jfgiraud_jlinenoise_JLinenoiseLibrary
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jfgiraud_jlinenoise_JLinenoiseLibrary_print
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jfgiraud_jlinenoise_JLinenoiseLibrary
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jfgiraud_jlinenoise_JLinenoiseLibrary_init
  (JNIEnv *, jobject);

/*
 * Class:     com_github_jfgiraud_jlinenoise_JLinenoiseLibrary
 * Method:    linenoise
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jfgiraud_jlinenoise_JLinenoiseLibrary_linenoise
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
