name: CI

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "check out the repo"
              uses: actions/checkout@v3
            - name: "Test"
              run: |
                  make test
            - name: "make release"
              if: startsWith(github.ref, 'refs/tags/v')
              run: |
                  sudo make install-dependencies
                  make init
                  make archive REPOSITORY_NAME=${{ github.event.repository.name }}
            - name: "make package"
              if: startsWith(github.ref, 'refs/tags/v')
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
              run: |
                  mvn -B -DnewVersion=v$(cat doc/VERSION) -DgenerateBackupPoms=false versions:set
                  mvn --batch-mode deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: lib/${{ github.event.repository.name }}.jar
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
